name: fetch-repository-stats
concurrency: fetch-repository-stats

on:
  push:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-ghrs-with-matrix:
    name: repostats-for-nice-projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repositories to generate reports for.
        statsRepo: ['CSAFE-ISU/AOAS-2018-glass-manuscript', 'samia067/shoerinsics', 'UCIDataLab/uci-digital-evidence/', 'CSAFE-ISU/shoeprintr', 'heike/bulletxtrctr', 'xhtai/cartridges', 'heike/grooveFinder', 'xhtai/heisenbrgr', 'UCIDataLab/assocr', 'CSAFE-ISU/handwriter', 'zout3/overlapping-ellipses-recognition']
      # Do not cancel&fail all remaining jobs upon first job failure.
      fail-fast: false
      # Help avoid commit conflicts. Note(JP): this should not be
      # necessary anymore, feedback appreciated
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.API_TOKEN_GITHUB }}
